<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMap [
        <!ELEMENT sqlMap (sql*)>
        <!ELEMENT sql (#PCDATA)>
        <!ATTLIST sql id  CDATA #REQUIRED>
        ]>
<sqlMap>
    <!-- 工作流外部系统信息表 对应的语句按照 字段顺序识别，所以顺序不能错，名称可以不一致 -->
    <sql id="WORKFLOW_EXTERNAL_USERINFO">
        <![CDATA[
            select USER_CODE, USER_NAME , PRIMARY_UNIT, USER_ORDER
            from F_USERINFO where ISVALID='T' order by USER_ORDER
        ]]>
    </sql>

    <sql id="WORKFLOW_EXTERNAL_UNITINFO">
        <![CDATA[
            select UNIT_CODE, PARENT_UNIT, UNIT_NAME,
                   UNIT_MANAGER, UNIT_ORDER, UNIT_PATH
            from F_UNITINFO where ISVALID='T' order by UNIT_ORDER
        ]]>
    </sql>

    <sql id="WORKFLOW_EXTERNAL_USERUNIT">
        <![CDATA[
            select UNIT_CODE, USER_CODE,
                   USER_STATION, USER_RANK,
                   IS_PRIMARY as isPrimary, USER_ORDER as userOrder
            from F_USERUNIT
        ]]>
    </sql>

    <sql id="WORKFLOW_EXTERNAL_USERROLE">
        <![CDATA[
            select USER_CODE, ROLE_CODE,
            'D' as OBTAIN_TYPE, '' as inherited_From
            from F_USERROLE
        ]]>
    </sql>

    <sql id="WORKFLOW_EXTERNAL_RANK_INFO">
        <![CDATA[
            select DATA_CODE as RANK_CODE, DATA_VALUE as RANK_NAME, EXTRA_CODE as RANK
            from F_DATADICTIONARY where CATALOG_CODE = 'RankType'
        ]]>
    </sql>

    <sql id="WORKFLOW_EXTERNAL_STATION_INFO">
        <![CDATA[
            select DATA_CODE as STATION_CODE, DATA_VALUE as STATION_NAME
            from F_DATADICTIONARY where CATALOG_CODE = 'StationType'
        ]]>
    </sql>

    <sql id="WORKFLOW_EXTERNAL_ITEM_ROLE">
        <![CDATA[
            select DATA_CODE as RANK_CODE, EXTRA_CODE as RANK
            from F_DATADICTIONARY where CATALOG_CODE = 'FlowUserRole'
        ]]>
    </sql>

    <sql id="WORKFLOW_EXTERNAL_ROLE_INFO">
        <![CDATA[
            select ROLE_CODE, ROLE_NAME
            from F_ROLEINFO where IS_VALID = 'T'
        ]]>
    </sql>

</sqlMap>
